spring.application.name=game-backlog-backend

rawg.api.key=${RAWG_API_KEY}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
