spring.application.name=game-backlog-backend

rawg.api.key=${RAWG_API_KEY}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
