spring.application.name=game-backlog-backend

game.provider=IGDB

rawg.api.key=${RAWG_API_KEY}

igdb.client.id=${IGDB_CLIENT_ID}
igdb.client.secret=${IGDB_CLIENT_SECRET}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
